"""
watch-papers.py
Watches "AI papers for WebProject1" for new PDFs, regenerates papers-manifest.js,
serves the site over HTTP, and auto-reloads any open browser tabs.

Usage:
    python watch-papers.py          # serve + watch (open http://localhost:5500/index.html)
    python watch-papers.py --once   # one-shot manifest update only, no server
"""

import os
import sys
import json
import time
import datetime
import threading
from http.server import HTTPServer, SimpleHTTPRequestHandler
from queue import Queue, Empty

FOLDER = "AI papers for WebProject1"
MANIFEST_JS   = "papers-manifest.js"
MANIFEST_JSON = "papers-manifest.json"
POLL_INTERVAL = 5   # seconds between folder checks
PORT = 5500

# Per-client queues for SSE reload signals
_sse_clients = []
_sse_lock = threading.Lock()


def get_pdf_files():
    try:
        return sorted(f for f in os.listdir(FOLDER) if f.lower().endswith(".pdf"))
    except FileNotFoundError:
        print(f"Folder not found: {FOLDER}")
        return []


def load_sidecar_metadata(files):
    """Read a .json sidecar for each PDF (same base name, same folder).
    Returns a dict mapping filename → metadata dict.
    Parse errors are caught per-file so a bad JSON never blocks the manifest."""
    metadata = {}
    for fname in files:
        base = os.path.splitext(fname)[0]
        jpath = os.path.join(FOLDER, base + ".json")
        if not os.path.exists(jpath):
            continue
        try:
            with open(jpath, "r", encoding="utf-8") as f:
                data = json.load(f)
            # Only keep known safe fields — never let sidecar inject id/groups/isLocal
            metadata[fname] = {k: data[k] for k in
                ("title", "authors", "year", "preview", "summary",
                 "datacenter", "metrics", "link")
                if k in data}
        except Exception as e:
            print(f"  [warn] Could not read sidecar {jpath}: {e}")
    return metadata


def write_manifest(files):
    now = datetime.datetime.now()
    metadata = load_sidecar_metadata(files)

    # JS version — loaded as a <script> tag at page load
    lines = [
        "// Auto-generated by watch-papers.py — do not edit by hand",
        f"// Updated: {now.isoformat()}",
        "window.localPapersManifest =",
        json.dumps(files, indent=2) + ";",
    ]
    with open(MANIFEST_JS, "w", encoding="utf-8") as fp:
        fp.write("\n".join(lines) + "\n")

    # JSON version — polled via fetch() by the running page for live updates
    # "metadata" key maps each PDF filename to its sidecar fields.
    payload = {"files": files, "updated": now.isoformat(), "metadata": metadata}
    with open(MANIFEST_JSON, "w", encoding="utf-8") as fp:
        json.dump(payload, fp, indent=2)

    rich = sum(1 for f in files if f in metadata)
    print(f"[{now.strftime('%H:%M:%S')}] Manifest updated — {len(files)} PDFs ({rich} with metadata)")


def notify_clients():
    with _sse_lock:
        for q in list(_sse_clients):
            try:
                q.put("reload")
            except Exception:
                pass


class Handler(SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/changes":
            # Server-Sent Events endpoint for live reload
            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            q = Queue()
            with _sse_lock:
                _sse_clients.append(q)
            try:
                while True:
                    try:
                        msg = q.get(timeout=25)
                        self.wfile.write(f"data: {msg}\n\n".encode())
                        self.wfile.flush()
                    except Empty:
                        # Heartbeat keeps the connection alive through proxies
                        self.wfile.write(b": ping\n\n")
                        self.wfile.flush()
            except Exception:
                pass
            finally:
                with _sse_lock:
                    try:
                        _sse_clients.remove(q)
                    except ValueError:
                        pass
        else:
            super().do_GET()

    def log_message(self, format, *args):
        pass  # suppress per-request noise


def watch_loop():
    last_files = None
    while True:
        files = get_pdf_files()
        if files != last_files:
            write_manifest(files)
            if last_files is not None:  # skip reload on first startup
                print(f"[{datetime.datetime.now().strftime('%H:%M:%S')}] New PDFs detected — signalling browser reload")
                notify_clients()
            last_files = files
        time.sleep(POLL_INTERVAL)


def main():
    if "--once" in sys.argv:
        write_manifest(get_pdf_files())
        return

    # Watcher runs on a background daemon thread
    threading.Thread(target=watch_loop, daemon=True).start()

    server = HTTPServer(("", PORT), Handler)
    print(f"\n  Open: http://localhost:{PORT}/index.html")
    print(f"  Watching '{FOLDER}' for new PDFs every {POLL_INTERVAL}s")
    print("  Drop a PDF in the folder — the browser tab will reload automatically.")
    print("  Press Ctrl+C to stop.\n")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")


if __name__ == "__main__":
    main()
